{"name": "Test error handling and recovery", "status": "passed", "description": "Verify proper error handling across the framework.", "steps": [{"name": "Test error scenarios", "status": "passed", "attachments": [{"name": "Status", "source": "e5f9305b-fa27-4ba2-b6c2-2d5e5133256b-attachment.txt", "type": "text/plain"}], "start": 1757433931369, "stop": 1757433931369}], "start": 1757433931369, "stop": 1757433931370, "uuid": "06c59cde-4272-4935-b57b-5afa6ed62f50", "historyId": "9008ee63ea92bf03a8e2321a03a032d3", "testCaseId": "9008ee63ea92bf03a8e2321a03a032d3", "fullName": "tests.test_regression.TestAutomationFrameworkRegression#test_error_handling", "labels": [{"name": "feature", "value": "Regression Testing"}, {"name": "tag", "value": "regression"}, {"name": "epic", "value": "Automation Framework"}, {"name": "severity", "value": "normal"}, {"name": "story", "value": "Error Handling"}, {"name": "tag", "value": "error-handling"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_regression"}, {"name": "subSuite", "value": "TestAutomationFrameworkRegression"}, {"name": "host", "value": "EvilBookPro.local"}, {"name": "thread", "value": "28769-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_regression"}]}