{"name": "Test error handling and recovery", "status": "passed", "description": "Verify proper error handling across the framework.", "steps": [{"name": "Test error scenarios", "status": "passed", "attachments": [{"name": "Status", "source": "ca3e77bd-3026-4be3-a610-85e046e0f413-attachment.txt", "type": "text/plain"}], "start": 1757433942748, "stop": 1757433942748}], "start": 1757433942748, "stop": 1757433942748, "uuid": "dcc39073-70fa-44c3-9e0e-ad95ef721032", "historyId": "9008ee63ea92bf03a8e2321a03a032d3", "testCaseId": "9008ee63ea92bf03a8e2321a03a032d3", "fullName": "tests.test_regression.TestAutomationFrameworkRegression#test_error_handling", "labels": [{"name": "epic", "value": "Automation Framework"}, {"name": "feature", "value": "Regression Testing"}, {"name": "tag", "value": "regression"}, {"name": "severity", "value": "normal"}, {"name": "story", "value": "Error Handling"}, {"name": "tag", "value": "error-handling"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_regression"}, {"name": "subSuite", "value": "TestAutomationFrameworkRegression"}, {"name": "host", "value": "EvilBookPro.local"}, {"name": "thread", "value": "29064-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_regression"}]}